### ISSUE TITLE
Can't use UNIXClientEndpoint with flowFountFromEndpoint

### ISSUE THREAD

**Issue by jMyles** [twisted/tubes#83] opened 2019-02-26 20:08 UTC
Still trying to wrap my head around the whole metaphor here.

I (perhaps mistakenly) assumed that `flowFountFromEndpoint` was a way to get a fount from an endpoint.  However, it doesn't seem to work with a `UNIXClientEndpoint` because it doesn't implement `listen`:

`builtins.AttributeError: 'UNIXClientEndpoint' object has no attribute 'listen'`.

Is it better for me to use `flowFromEndpoint`?  And then pass the resulting `flow` into my listener directly (rather than using `flowTo`)?  In that case, how do I handle incoming messages?

Or am I just way off?

**Comment by glyph** [comment] 2019-08-03 22:04
`flowFountFromEndpoint` is the way to get a *fount of flows* from a *server*, i.e. listening, stream endpoint.  It specifies this in its `@type endpoint: L{IStreamServerEndpoint}`, which you can see documented here: https://twistedmatrix.com/documents/19.2.1/api/twisted.internet.interfaces.IStreamServerEndpoint.html

This is muddled a bit by the fact that the docstring has a typo in it and referrs to a "`C{connect} method`", so that should be fixed.

`UNIXClientEndpoint` is a client endpoint, and is therefore something you would use with `flowFromEndpoint`.  `flowFromEndpoint` does *not* document the `@type`, of its argument, but it should!   it's IStreamClientEndpoint: https://twistedmatrix.com/documents/19.2.1/api/twisted.internet.interfaces.IStreamClientEndpoint.html

**Comment by glyph** [comment] 2019-08-03 22:05
While there are issues with the docs here, I'm closing this issue because the fundamental question being asked here is just a `TypeError` and it's working as designed.

**Closed by glyph** 2019-08-03 22:05 UTC
